### ISSUE TITLE
EBP org?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-exercise#1]
Feel free to develop this underneath the `executablebooks` organization (if you wish!)...just trying to minimize extra switch-over work later on

**Comment by najuzilu** [comment]
I'm going to move it over as soon as I fix references. :-)

**Comment by najuzilu** [comment]
Just moved this over to EBP so I'm going to close this issue. :-)

**Comment by choldgraf** [comment]
yahoo 🎉
