### ISSUE TITLE
Make bottom/top padding the same as admonitions

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-exercise#10]
I noticed that if we toggle the exercises / solutions like so:

````
```{solution} mylabel
:class: dropdown
Some solution
```
````

Then there's extra whitespace for the solution when it is toggle.

ex:

![image](https://user-images.githubusercontent.com/1839645/95493971-0cb3a480-0952-11eb-8f3d-e30a38c08def.png)

I think that's because we're setting solution/exercise `div`s to have `padding: .6rem 1rem;`. Could we keep the top/bottom padding the same as the other admonitions so that this doesn't occur? Alternatively, we could add another CSS rule to make the padding 0 when underneath a collapsed dropdown.

**Comment by najuzilu** [comment]
I really wanted to try this! Awesome test case @choldgraf. I'll fix this for both this extension and [sphinxcontrib-prettyproof](https://github.com/executablebooks/sphinxcontrib-prettyproof).

**Comment by najuzilu** [comment]
@choldgraf how's this: [sphinx-exercise.readthedocs.io/en/latest/syntax.html#how-to-hide-directives](https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html#how-to-hide-directives)

**Comment by choldgraf** [comment]
it looks great!
