### ISSUE TITLE
Links to the exercise should only be the title of that exercise

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-exercise#12]
I noticed that in the solution directive, the entire title of it links back to the exercise:

![image](https://user-images.githubusercontent.com/1839645/95494294-8e0b3700-0952-11eb-9930-02b1cc63c5c0.png)

I think that this is a great feature, but I worry that by making the whole solution title link out, it will make readers think that the link is *to the solution* rather than *to the exercise*.

What do you think about either:

- Making only the `Exercise 1` portion above linked, then making the color of that link the normal link color so that users know it is a link
- Adding a `(source)` to the end of the title or to the top of the body that links back to the exercise

**Comment by najuzilu** [comment]
I could go with either one. What do @jstac @mmcky think?

**Comment by jstac** [comment]
Option 1 sounds good to me.

**Comment by kanderso-nrel** [comment]
Howdy, I think this issue may have been unintentionally un-fixed somewhere along the way -- the entire "Solution to Exercise 1" text is within the link in the `latest` docs example: https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html#solution-directive

**Comment by mmcky** [comment]
thanks for reporting this @kanderso-nrel. 

So you are looking for something like:

Solution to [Exercise 1]()

instead?

**Comment by kanderso-nrel** [comment]
Yes, that's what seems the best to me.  And it seems like this thread concluded the same back in 2020.

**Comment by mmcky** [comment]
@kanderso-nrel this has now been fixed. I'll organise a new release now for the package. 

![Screen Shot 2022-02-01 at 4 51 26 pm](https://user-images.githubusercontent.com/8263752/151919281-46441ead-c38c-429c-8031-0ba70d238cd5.png)

**Comment by mmcky** [comment]
@kanderso-nrel the updated package is now available on `pypi`.

**Comment by kanderso-nrel** [comment]
Thanks @mmcky! Just a heads up, it seems that RTD did not run for the new version: https://readthedocs.org/projects/ebp-sphinx-exercise/builds/

**Comment by mmcky** [comment]
thanks @kanderso-nrel -- I just issued a manual rebuild. Not sure why it didn't trigger. Will look into it.
