### ISSUE TITLE
[ENH] Add solution block with linking to an exercise

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-exercise#19]
From executablebooks/sphinx-proof#17 

In addition to exercise, could we please have solution?

The styling can be the same as proof.

Even more awsome would be {proof:solution:exercise_label} or some other syntax --- whatever works --- that produces

"Solution to Exercise X"

as a header and then gives the same styling as proof. 

---

I wonder if these sort of features should eventually make their way into an independent extension for exercises/solution blocks.

**Comment by najuzilu** [comment]
This has been addressed :tada:
