### ISSUE TITLE
Add a "logo" similarly to other content blocks in sphinx

### ISSUE THREAD

**Issue by fmaussion** [executablebooks/sphinx-exercise#22]
Content boxes usually have some kind of logo or character drawing attention to them:

![image](https://user-images.githubusercontent.com/10050469/95658259-4c78b880-0b19-11eb-862d-ceb7c4868917.png)

![image](https://user-images.githubusercontent.com/10050469/95658268-5bf80180-0b19-11eb-8fee-3d3012a207b4.png)

Having something similar for sphinx-exercise would be great!!! A possible one would be: https://fontawesome.com/icons/user-edit?style=solid

**Comment by najuzilu** [comment]
What do you think? @fmaussion @jstac @mmcky @choldgraf

Option 1
<img width="821" alt="Screen Shot 2020-10-13 at 5 04 19 PM" src="https://user-images.githubusercontent.com/33075058/95879186-5a774500-0d76-11eb-8b92-481ed984c682.png">

Option 2
<img width="823" alt="Screen Shot 2020-10-13 at 5 04 48 PM" src="https://user-images.githubusercontent.com/33075058/95879194-5cd99f00-0d76-11eb-9c3e-9f621e0b3f5a.png">

Option 3
<img width="826" alt="Screen Shot 2020-10-13 at 5 05 17 PM" src="https://user-images.githubusercontent.com/33075058/95879198-5d723580-0d76-11eb-8cf6-166e2d441cb0.png">

**Comment by choldgraf** [comment]
I think I prefer 1! (the other two icons are often used to denote something that is "editable")

**Comment by mmcky** [comment]
I think `option 3` looks less cluttered - but I am happy to follow @choldgraf reasoning on this.

**Comment by jstac** [comment]
I prefer option 3 for the reason @mmcky gives.

**Comment by choldgraf** [comment]
(FWIW I'm happy with option 3 as well!)
