### ISSUE TITLE
docs should include that `sphinx_book_theme` is required

### ISSUE THREAD

**Issue by goekce** [executablebooks/sphinx-exercise#38]
### Description / Summary

Without `html_theme = 'sphinx_book_theme'` in `conf.py` the exercise and solutions lack the icons on the top left side. It would be great if this theme is recommended in https://ebp-sphinx-exercise.readthedocs.io/en/latest/index.html#sphinx-project

To see the issue use the default theme `html_theme = 'alabaster'`

### Value / benefit

People who are new to this project would spend less time for debugging :)

**Comment by mmcky** [comment]
thanks @goekce -- sorry this took me so long to get to. 

I have now added this to the docs and opened #52
