### ISSUE TITLE
ENH: Add support for gated exercise directives

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-exercise#55]
### Describe the problem/need and solution

Similar to `gated solution` directives implemented in #45 it would be nice to have that same syntax available for `exercise` directives. 

### Guide for implementation

Similar to `transform` structure in #45 

### Tasks and updates

- [ ] required by https://github.com/QuantEcon/lecture-python-programming.myst/pull/176

**Comment by psychemedia** [comment]
It would be really nice to have abstracted classes for gated directives on which custom directives (including exercise and solution) could build to added gated support.

**Comment by mmcky** [comment]
this will be closed by #45

**Comment by psychemedia** [comment]
I also wonder - how does the gated admonition relate to things like the emerging official MyST spec? https://github.com/executablebooks/myst-spec/
