### ISSUE TITLE
Some tests fails with sphinx-4.5.0

### ISSUE THREAD

**Issue by vincentxavier** [executablebooks/sphinx-exercise#59]
### Describe the bug

**context**
When I do `python -m pytest`.

**expectation**
I expected all tests to pass.

**bug**
But instead some tests fails.

In particular, `<div class="section" id="…" >` is now replaced by `<section id="…">`

**problem**
This is a problem for people doing development because test should be reliable.

### Reproduce the bug

1. install sphinx-4.5.0
2. launch the test suite

**Comment by AakashGfude** [comment]
Thanks, @vincentxavier for bringing this up. Should be fixed in this PR: https://github.com/executablebooks/sphinx-exercise/pull/60
